run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nakedret
    - noctx
    - bodyclose
    - errorlint
    - gosec
    - prealloc
    - nolintlint
    - wastedassign
    - predeclared
    - dupword
    - tenv
    - gci

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  nakedret:
    max-func-lines: 30
  goimports:
    local-prefixes: github.com/chronicle-db/chronicle
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G304  # File path from variable (expected in DB)
  nolintlint:
    require-explanation: true
    require-specific: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/chronicle-db/chronicle)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - prealloc
        - tenv
        - dupword
