// Code generated by gen_feature_accessors.go; DO NOT EDIT.

package chronicle

// CQLEngine returns the CQLEngine instance (lazy-initialized).
func (fm *FeatureManager) CQLEngine() *CQLEngine {
	fm.cqlEngineOnce.Do(func() {
		safeInit("cql", func() {
			fm.cqlEngine = NewCQLEngine(fm.db, fm.cqlConfig)
		})
	})
	return fm.cqlEngine
}

// Observability returns the ObservabilitySuite instance (lazy-initialized).
func (fm *FeatureManager) Observability() *ObservabilitySuite {
	fm.observabilityOnce.Do(func() {
		safeInit("observability", func() {
			fm.observability = NewObservabilitySuite(fm.observabilityConfig)
		})
	})
	return fm.observability
}

// MaterializedViews returns the MaterializedViewEngine instance (lazy-initialized).
func (fm *FeatureManager) MaterializedViews() *MaterializedViewEngine {
	fm.materializedViewsOnce.Do(func() {
		safeInit("materialized_views", func() {
			fm.materializedViews = NewMaterializedViewEngine(fm.db, fm.materializedViewsConfig)
		})
	})
	return fm.materializedViews
}

// ChaosInjector returns the FaultInjector instance (lazy-initialized).
func (fm *FeatureManager) ChaosInjector() *FaultInjector {
	fm.chaosInjectorOnce.Do(func() {
		safeInit("chaos", func() {
			fm.chaosInjector = NewFaultInjector(DefaultChaosConfig())
		})
	})
	return fm.chaosInjector
}

// OfflineSync returns the OfflineSyncManager instance (lazy-initialized).
func (fm *FeatureManager) OfflineSync() *OfflineSyncManager {
	fm.offlineSyncOnce.Do(func() {
		safeInit("offline_sync", func() {
			fm.offlineSync = NewOfflineSyncManager(DefaultOfflineSyncConfig())
		})
	})
	return fm.offlineSync
}

// AnomalyPipeline returns the AnomalyPipeline instance (lazy-initialized).
func (fm *FeatureManager) AnomalyPipeline() *AnomalyPipeline {
	fm.anomalyPipelineOnce.Do(func() {
		safeInit("anomaly_pipeline", func() {
			fm.anomalyPipeline = NewAnomalyPipeline(fm.db, DefaultAnomalyPipelineConfig())
		})
	})
	return fm.anomalyPipeline
}

// AnomalyCorrelation returns the AnomalyCorrelationEngine instance (lazy-initialized).
func (fm *FeatureManager) AnomalyCorrelation() *AnomalyCorrelationEngine {
	fm.anomalyCorrelationOnce.Do(func() {
		safeInit("anomaly_correlation", func() {
			fm.anomalyCorrelation = NewAnomalyCorrelationEngine(fm.db, DefaultAnomalyCorrelationConfig())
		})
	})
	return fm.anomalyCorrelation
}

// CloudRelay returns the CloudRelay instance (lazy-initialized).
func (fm *FeatureManager) CloudRelay() *CloudRelay {
	fm.cloudRelayOnce.Do(func() {
		safeInit("cloud_relay", func() {
			fm.cloudRelay = NewCloudRelay(fm.db, DefaultCloudRelayConfig())
		})
	})
	return fm.cloudRelay
}

// Playground returns the Playground instance (lazy-initialized).
func (fm *FeatureManager) Playground() *Playground {
	fm.playgroundOnce.Do(func() {
		safeInit("playground", func() {
			fm.playground = NewPlayground(fm.db, DefaultPlaygroundConfig())
		})
	})
	return fm.playground
}

// QueryPlanner returns the QueryPlanner instance (lazy-initialized).
func (fm *FeatureManager) QueryPlanner() *QueryPlanner {
	fm.queryPlannerOnce.Do(func() {
		safeInit("query_planner", func() {
			fm.queryPlanner = NewQueryPlanner(fm.db, DefaultQueryPlannerConfig())
		})
	})
	return fm.queryPlanner
}

// ConnectorHub returns the ConnectorHub instance (lazy-initialized).
func (fm *FeatureManager) ConnectorHub() *ConnectorHub {
	fm.connectorHubOnce.Do(func() {
		safeInit("connector_hub", func() {
			fm.connectorHub = NewConnectorHub(fm.db, DefaultConnectorHubConfig())
		})
	})
	return fm.connectorHub
}

// Autoscaler returns the PredictiveAutoscaler instance (lazy-initialized).
func (fm *FeatureManager) Autoscaler() *PredictiveAutoscaler {
	fm.autoscalerOnce.Do(func() {
		safeInit("autoscaler", func() {
			fm.autoscaler = NewPredictiveAutoscaler(fm.db, DefaultPredictiveAutoscalingConfig())
		})
	})
	return fm.autoscaler
}

// NotebookEngine returns the NotebookEngine instance (lazy-initialized).
func (fm *FeatureManager) NotebookEngine() *NotebookEngine {
	fm.notebookEngineOnce.Do(func() {
		safeInit("notebooks", func() {
			fm.notebookEngine = NewNotebookEngine(fm.db, DefaultNotebookConfig())
		})
	})
	return fm.notebookEngine
}

// SaaSControlPlane returns the SaaSControlPlane instance (lazy-initialized).
func (fm *FeatureManager) SaaSControlPlane() *SaaSControlPlane {
	fm.saasControlPlaneOnce.Do(func() {
		safeInit("saas_control_plane", func() {
			fm.saasControlPlane = NewSaaSControlPlane(fm.db, DefaultSaaSControlPlaneConfig())
		})
	})
	return fm.saasControlPlane
}

// GitOpsEngine returns the GitOpsEngine instance (lazy-initialized).
func (fm *FeatureManager) GitOpsEngine() *GitOpsEngine {
	fm.gitopsEngineOnce.Do(func() {
		safeInit("gitops", func() {
			fm.gitopsEngine = NewGitOpsEngine(fm.db, DefaultGitOpsConfig())
		})
	})
	return fm.gitopsEngine
}

// FederatedMLTrainer returns the FederatedMLTrainer instance (lazy-initialized).
func (fm *FeatureManager) FederatedMLTrainer() *FederatedMLTrainer {
	fm.federatedMLOnce.Do(func() {
		safeInit("federated_ml", func() {
			fm.federatedML = NewFederatedMLTrainer(fm.db, DefaultFederatedMLConfig())
		})
	})
	return fm.federatedML
}

// QueryCompiler returns the QueryCompiler instance (lazy-initialized).
func (fm *FeatureManager) QueryCompiler() *QueryCompiler {
	fm.queryCompilerOnce.Do(func() {
		safeInit("query_compiler", func() {
			fm.queryCompiler = NewQueryCompiler(fm.db, DefaultQueryCompilerConfig())
		})
	})
	return fm.queryCompiler
}

// EdgePlatform returns the EdgePlatformManager instance (lazy-initialized).
func (fm *FeatureManager) EdgePlatform() *EdgePlatformManager {
	fm.edgePlatformOnce.Do(func() {
		safeInit("edge_platform", func() {
			fm.edgePlatform = NewEdgePlatformManager()
		})
	})
	return fm.edgePlatform
}

// TSRAG returns the TSRAGEngine instance (lazy-initialized).
func (fm *FeatureManager) TSRAG() *TSRAGEngine {
	fm.tsRAGOnce.Do(func() {
		safeInit("ts_rag", func() {
			fm.tsRAG = NewTSRAGEngine(fm.db, DefaultTSRAGConfig())
		})
	})
	return fm.tsRAG
}

// PluginRegistry returns the PluginRegistry instance (lazy-initialized).
func (fm *FeatureManager) PluginRegistry() *PluginRegistry {
	fm.pluginRegistryOnce.Do(func() {
		safeInit("plugin_registry", func() {
			fm.pluginRegistry = NewPluginRegistry(DefaultPluginSDKConfig())
		})
	})
	return fm.pluginRegistry
}
