"""Type stubs for chronicle Python SDK."""

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional, Union


@dataclass
class Point:
    metric: str
    value: float
    tags: Dict[str, str] = ...
    timestamp: int = ...
    @classmethod
    def from_datetime(cls, metric: str, value: float, tags: Optional[Dict[str, str]] = ..., dt: Optional[datetime] = ...) -> "Point": ...
    def to_datetime(self) -> datetime: ...


@dataclass
class Config:
    path: str
    retention_hours: int = ...
    partition_duration_hours: int = ...
    max_series: int = ...
    enable_compression: bool = ...
    enable_wal: bool = ...


class ChronicleError(Exception):
    code: int
    message: str
    def __init__(self, code: int, message: str) -> None: ...


class Chronicle:
    def __init__(self, path: str, config: Optional[Config] = ..., lib_path: Optional[str] = ...) -> None: ...
    def __enter__(self) -> "Chronicle": ...
    def __exit__(self, *args: Any) -> None: ...
    def close(self) -> None: ...
    def write(self, point: Point) -> None: ...
    def write_batch(self, points: List[Point]) -> None: ...
    def query(self, metric: str, tags: Optional[Dict[str, str]] = ..., start: int = ..., end: int = ..., limit: int = ...) -> List[Point]: ...
    def query_sql(self, sql: str) -> List[Point]: ...
    def flush(self) -> None: ...
    def metrics(self) -> List[str]: ...
    def stats(self) -> Dict[str, Any]: ...
