name: Good First Issue
description: A well-scoped task for new contributors
labels: ["good first issue", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in contributing to Chronicle!
        Good first issues are designed to be approachable for newcomers.
  - type: textarea
    id: description
    attributes:
      label: What needs to be done
      description: Clear, actionable description of the task
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context and relevant files
      description: Which files to look at and any background information
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How we'll know the task is complete
      value: |
        - [ ] Code compiles (`go build ./...`)
        - [ ] Tests pass (`go test -short ./...`)
        - [ ] New test added if applicable
    validations:
      required: true
