//go:build ignore
// +build ignore

// gen_feature_accessors generates lazy-init accessor methods for FeatureManager.
//
// Usage:
//
//	go run scripts/gen_feature_accessors.go -out feature_manager_gen.go
//
// Each feature definition specifies:
//   - Method: exported accessor name (e.g., "CQLEngine")
//   - Type: return type (e.g., "CQLEngine")
//   - Field: struct field name (e.g., "cqlEngine")
//   - InitName: name passed to safeInit (e.g., "cql")
//   - Constructor: Go expression for initialization (e.g., "NewCQLEngine(fm.db, fm.cqlConfig)")
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"text/template"
)

type Feature struct {
	Method      string // Exported method name
	Type        string // Return pointer type
	Field       string // Struct field name
	InitName    string // Name for safeInit logging
	Constructor string // Constructor expression
}

// features defines all lazy-init features.
// Add new features here and run go generate to update the accessor methods.
var features = []Feature{
	{"CQLEngine", "CQLEngine", "cqlEngine", "cql", "NewCQLEngine(fm.db, fm.cqlConfig)"},
	{"Observability", "ObservabilitySuite", "observability", "observability", "NewObservabilitySuite(fm.observabilityConfig)"},
	{"MaterializedViews", "MaterializedViewEngine", "materializedViews", "materialized_views", "NewMaterializedViewEngine(fm.db, fm.materializedViewsConfig)"},
	{"ChaosInjector", "FaultInjector", "chaosInjector", "chaos", "NewFaultInjector(DefaultChaosConfig())"},
	{"OfflineSync", "OfflineSyncManager", "offlineSync", "offline_sync", "NewOfflineSyncManager(DefaultOfflineSyncConfig())"},
	{"AnomalyPipeline", "AnomalyPipeline", "anomalyPipeline", "anomaly_pipeline", "NewAnomalyPipeline(fm.db, DefaultAnomalyPipelineConfig())"},
	{"AnomalyCorrelation", "AnomalyCorrelationEngine", "anomalyCorrelation", "anomaly_correlation", "NewAnomalyCorrelationEngine(fm.db, DefaultAnomalyCorrelationConfig())"},
	{"CloudRelay", "CloudRelay", "cloudRelay", "cloud_relay", "NewCloudRelay(fm.db, DefaultCloudRelayConfig())"},
	{"Playground", "Playground", "playground", "playground", "NewPlayground(fm.db, DefaultPlaygroundConfig())"},
	{"QueryPlanner", "QueryPlanner", "queryPlanner", "query_planner", "NewQueryPlanner(fm.db, DefaultQueryPlannerConfig())"},
	{"ConnectorHub", "ConnectorHub", "connectorHub", "connector_hub", "NewConnectorHub(fm.db, DefaultConnectorHubConfig())"},
	{"Autoscaler", "PredictiveAutoscaler", "autoscaler", "autoscaler", "NewPredictiveAutoscaler(fm.db, DefaultPredictiveAutoscalingConfig())"},
	{"NotebookEngine", "NotebookEngine", "notebookEngine", "notebooks", "NewNotebookEngine(fm.db, DefaultNotebookConfig())"},
	{"SaaSControlPlane", "SaaSControlPlane", "saasControlPlane", "saas_control_plane", "NewSaaSControlPlane(fm.db, DefaultSaaSControlPlaneConfig())"},
	{"GitOpsEngine", "GitOpsEngine", "gitopsEngine", "gitops", "NewGitOpsEngine(fm.db, DefaultGitOpsConfig())"},
	{"FederatedMLTrainer", "FederatedMLTrainer", "federatedML", "federated_ml", "NewFederatedMLTrainer(fm.db, DefaultFederatedMLConfig())"},
	{"QueryCompiler", "QueryCompiler", "queryCompiler", "query_compiler", "NewQueryCompiler(fm.db, DefaultQueryCompilerConfig())"},
	{"EdgePlatform", "EdgePlatformManager", "edgePlatform", "edge_platform", "NewEdgePlatformManager()"},
	{"TSRAG", "TSRAGEngine", "tsRAG", "ts_rag", "NewTSRAGEngine(fm.db, DefaultTSRAGConfig())"},
	{"PluginRegistry", "PluginRegistry", "pluginRegistry", "plugin_registry", "NewPluginRegistry(DefaultPluginSDKConfig())"},
}

var accessorTmpl = template.Must(template.New("accessor").Parse(`
// {{.Method}} returns the {{.Type}} instance (lazy-initialized).
func (fm *FeatureManager) {{.Method}}() *{{.Type}} {
	fm.{{.Field}}Once.Do(func() {
		safeInit("{{.InitName}}", func() {
			fm.{{.Field}} = {{.Constructor}}
		})
	})
	return fm.{{.Field}}
}
`))

func main() {
	out := flag.String("out", "", "output file (default: stdout)")
	flag.Parse()

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gen_feature_accessors.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package chronicle\n\n")

	for _, f := range features {
		if err := accessorTmpl.Execute(&buf, f); err != nil {
			log.Fatalf("template: %v", err)
		}
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v", err)
	}

	if *out != "" {
		if err := os.WriteFile(*out, src, 0644); err != nil {
			log.Fatalf("write: %v", err)
		}
		fmt.Printf("Generated %d accessor methods in %s\n", len(features), *out)
	} else {
		os.Stdout.Write(src)
	}
}
